GENERAL_EXCEPTION = "internal_server_error"
LOGIN_EXCEPTION = "login_error"
REGISTER_EXCEPTION = "register_error"
NOT_AUTHORIZED = "not_authorized"
QUERY_PARAM_EXCEPTION = "query_param_error"
NOT_FOUND = "resource_not_found"
BAD_REQUEST_EXCEPTION = "bad_request_error"
